github: ayush-that
patreon: your-patreon-username
open_collective: your-open-collective-username
ko_fi: your-ko-fi-username
tidelift: npm/babel
community_bridge: cloud-foundry
liberapay: your-liberapay-username
issuehunt: your-issuehunt-username
lfx_crowdfunding: cloud-foundry
polar: your-polar-username
buy_me_a_coffee: your-buy-me-a-coffee-username
custom: ['link1', 'link2', 'link3', 'link4']