name: Style Changing Request
description: Suggest a style designs
title: '[style]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this template!
  - type: textarea
    id: style-idea
    attributes:
      label: What's the style idea?
      placeholder: Add descriptions
      value: 'We need to improve  '
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Add screenshots to see the demo
      placeholder: Add screenshots
      value: 'Add screenshots'
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
          required: true

        - label: I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
          required: true

        - label: I'm a GSSoC'24 contributor

        - label: I want to work on this issue
